#deployment file for our go-api server 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api 
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api-backend 
        image: go-api-backend:latest
        ports:
        - containerPort: 3000
        env:
          name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: USER
          name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PASSWORD
          name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_NAME
          name: POSTGRES_DB_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PORT
-
---
apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  selector:
    app.kubernetes.io/name: go-api
  ports:
    - protocol: TCP
      port: 8080 # port that is exposed 
      targetPort: 3000 #the port where r
