version : '2.23'

services:
  backend:
    build: .
    depends_on: 
      - postgres
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    

  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      

