#deployment and service for postgres DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgresdb 
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: USER
          name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PASSWORD
          name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_NAME
          name: POSTGRES_DB_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - protocol: TCP
      port: 8080 # port that is exposed 
      targetPort: 5432 #the port where request is to be forwarded
