#deployment and service for postgres DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgresdb 
        image: postgres:17.0
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_LISTEN_ADDRESSES
            value: "*"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
          - name: POSTGRES_USER
            value: sid
          - name: POSTGRES_PASSWORD
            value: postgresPW
          - name: POSTGRES_DB
            value: sample-db
        #   - name: POSTGRES_USER
        #     valueFrom:
        #       secretKeyRef:
        #         name: postgres-secret
        #         key: USER
        #   - name: POSTGRES_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: postgres-secret
        #         key: PASSWORD
        #   - name: POSTGRES_DB
        #     valueFrom:
        #       secretKeyRef:
        #         name: postgres-secret
        #         key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # port that is exposed 
      targetPort: 5432 #the port where request is to be forwarded
